Script started on 2025-05-10 09:46:32+00:00 [TERM="xterm-256color" TTY="/dev/pts/10" COLUMNS="197" LINES="13"]
]0;vchan26@gn-16-30-00:~/ECE491B/assignment4-hpc[?2004h]633;A(eceassignment1) ]633;A]633;A]633;A[vchan26@gn-16-30-00 assignment4-hpc]$ ]633;B]633;B]633;B]633;Bpytest --color=no
[?2004l======================================================================================== test session starts ========================================================================================
platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/vchan26/ECE491B/assignment4-hpc
plugins: anyio-4.9.0
collecting ... collecting 2 items                                                                                                                                                                                  collected 10 items                                                                                                                                                                                  

cs336-systems/tests/test_ddp_individual_parameters.py ..                                                                                                                                      [ 20%]
cs336-systems/tests/test_rmsnorm.py ........                                                                                                                                                  [100%]

======================================================================================== 10 passed in 11.49s ========================================================================================
]0;vchan26@gn-16-30-00:~/ECE491B/assignment4-hpc[?2004h]633;A(eceassignment1) ]633;A]633;A]633;A[vchan26@gn-16-30-00 assignment4-hpc]$ ]633;B]633;B]633;B]633;Bexit
[?2004lexit

Script done on 2025-05-10 09:46:51+00:00 [COMMAND_EXIT_CODE="0"]
